version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install -r dev-requirements.txt
  build:
    commands:
      - pytest tests
artifacts:
  files:
    - '**/*'
